### ISSUE TITLE
Doesn't work when I pull & build

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-bpm-swagger#30]
When I do

`
mvn clean install -PrestDocs -PgenerateJson
`

I get an error: 

```
[INFO] ------------------------------------------------------------------------
[INFO] Building Camunda Swagger Docs Extractor Maven Plugin 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6:clean (default-clean) @ camunda-bpm-swagger-plugin-rest-docs ---
[INFO] Deleting C:\Temp\camunda-bpm-swagger\maven-plugin\rest-docs\target
[INFO]
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ camunda-bpm-swagger-plugin-rest-docs ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ camunda-bpm-swagger-plugin-rest-docs ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Temp\camunda-bpm-swagger\maven-plugin\rest-docs\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ camunda-bpm-swagger-plugin-rest-docs ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 9 source files to C:\Temp\camunda-bpm-swagger\maven-plugin\rest-docs\target\classes
[WARNING] /C:/Temp/camunda-bpm-swagger/maven-plugin/rest-docs/src/main/java/org/camunda/bpm/swagger/maven/interpreter/MarkDownDocumentInterpreter.java: Some input files use unchecked or unsafe operations.
[WARNING] /C:/Temp/camunda-bpm-swagger/maven-plugin/rest-docs/src/main/java/org/camunda/bpm/swagger/maven/interpreter/MarkDownDocumentInterpreter.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-plugin-plugin:3.5:descriptor (default-descriptor) @ camunda-bpm-swagger-plugin-rest-docs ---
[INFO] Using 'UTF-8' encoding to read mojo source files.
[INFO] java-javadoc mojo extractor found 0 mojo descriptor.
[INFO] java-annotations mojo extractor found 1 mojo descriptor.
[INFO]
[INFO] --- maven-plugin-plugin:3.5:helpmojo (default-descriptor) @ camunda-bpm-swagger-plugin-rest-docs ---
[INFO] Using 'UTF-8' encoding to read mojo source files.
[INFO] java-javadoc mojo extractor found 0 mojo descriptor.
[INFO] java-annotations mojo extractor found 1 mojo descriptor.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ camunda-bpm-swagger-plugin-rest-docs ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 51 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ camunda-bpm-swagger-plugin-rest-docs ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to C:\Temp\camunda-bpm-swagger\maven-plugin\rest-docs\target\test-classes
[WARNING] error reading C:\Users\ruecker\.m2\repository\org\assertj\assertj-core\3.8.0\assertj-core-3.8.0.jar; invalid LOC header (bad signature)
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ camunda-bpm-swagger-plugin-rest-docs ---
[INFO] Surefire report directory: C:\Temp\camunda-bpm-swagger\maven-plugin\rest-docs\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.camunda.bpm.swagger.maven.FileTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.098 sec
Running org.camunda.bpm.swagger.maven.GenerateDocumentationYamlMojoTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.464 sec <<< FAILURE!
generateSources(org.camunda.bpm.swagger.maven.GenerateDocumentationYamlMojoTest)  Time elapsed: 1.445 sec  <<< ERROR!
java.lang.NoClassDefFoundError: org/assertj/core/api/Assertions
        at org.camunda.bpm.swagger.maven.GenerateDocumentationYamlMojoTest.generateSources(GenerateDocumentationYamlMojoTest.java:34)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
        at org.apache.maven.plugin.testing.MojoRule$2.evaluate(MojoRule.java:308)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.ClassNotFoundException: org.assertj.core.api.Assertions
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 34 more


Results :

Tests in error:
  generateSources(org.camunda.bpm.swagger.maven.GenerateDocumentationYamlMojoTest): org/assertj/core/api/Assertions

Tests run: 2, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Camunda BPM Swagger ................................ SUCCESS [  1.503 s]
[INFO] Camunda Swagger Maven Plugin Root .................. SUCCESS [  1.167 s]
[INFO] Camunda Swagger Docs Extractor Maven Plugin ........ FAILURE [ 17.034 s]
[INFO] Camunda Swagger REST dictionary .................... SKIPPED
[INFO] Camunda Swagger Model Generator Maven Plugin ....... SKIPPED
[INFO] Camunda Swagger Spoon Maven Plugin ................. SKIPPED
[INFO] Camunda Swagger REST core model .................... SKIPPED
[INFO] Camunda Swagger JSON ............................... SKIPPED
[INFO] Camunda Swagger UI ................................. SKIPPED
[INFO] Camunda Swagger SpringBoot Example ................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20.517 s
[INFO] Finished at: 2017-09-25T20:47:44+02:00
[INFO] Final Memory: 37M/425M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project camunda-bpm-swagger-plugin-rest-docs: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Temp\camunda-bpm-swagger\maven-plugin\rest-docs\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :camunda-bpm-swagger-plugin-rest-docs

```

**Comment by jangalinski** [comment]
do you use Java 8? Just asking because problems with assertj are often caused by incompatibilities in that direction ...
What if you skip Tests?

**Comment by berndruecker** [comment]
Yes I use Java 8.
And yes, it works if I skip tests :-)

**Comment by zambrovski** [comment]
Interesting. It works for me. Will try with someone random.
